#!/bin/bash

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$ROOT/.codex/context/CODE_INDEX.md"
MODE="${1:---write}"

if [[ "$MODE" != "--write" && "$MODE" != "--check" ]]; then
    echo "Usage: $0 [--write|--check]" >&2
    exit 2
fi

mkdir -p "$(dirname "$OUTPUT")"
TMP="$(mktemp "${TMPDIR:-/tmp}/imprint-code-index.XXXXXX")"
FILES="$(mktemp "${TMPDIR:-/tmp}/imprint-code-files.XXXXXX")"
trap 'rm -f "$TMP" "$FILES"' EXIT

find "$ROOT" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' \) ! -path '*/.git/*' ! -path '*/.codex/*' -print | sort > "$FILES"

SOURCE_HASH="$(while IFS= read -r file; do shasum -a 256 "$file"; done < "$FILES" |
    shasum -a 256 | awk '{print $1}')"
BRANCH="$(git -C "$ROOT" branch --show-current 2>/dev/null || true)"
HEAD="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || true)"

{
    echo "# Code index"
    echo
    echo "Generated by scripts/update-context.sh. Do not edit manually."
    echo
    echo "- Source fingerprint: $SOURCE_HASH"
    echo "- Git position: ${BRANCH:-no-branch}@${HEAD:-no-commit}"
    echo
    echo "## Source files"
    echo
    echo "| File | Lines | Bytes | SHA-256 (12) |"
    echo "| --- | ---: | ---: | --- |"
    while IFS= read -r file; do
        rel="${file#"$ROOT/"}"
        lines="$(wc -l < "$file" | tr -d ' ')"
        bytes="$(wc -c < "$file" | tr -d ' ')"
        hash="$(shasum -a 256 "$file" | awk '{print substr($1,1,12)}')"
        echo "| $rel | $lines | $bytes | $hash |"
    done < "$FILES"
    echo
    echo "## HTML outline"
    echo
    find "$ROOT" -type f -name '*.html' ! -path '*/.git/*' ! -path '*/.codex/*' -print | sort |
        while IFS= read -r file; do
            rel="${file#"$ROOT/"}"
            echo
            echo "### $rel"
            rg -n --no-heading '<(title|h1|h2|h3)([ >])' "$file" 2>/dev/null || true
        done
    echo
    echo "## JavaScript declarations"
    echo
    find "$ROOT" -type f -name '*.js' ! -path '*/.git/*' ! -path '*/.codex/*' -print | sort |
        while IFS= read -r file; do
            rel="${file#"$ROOT/"}"
            rg -n --no-heading '^(const|let|var|function|class)[[:space:]]' "$file" 2>/dev/null |
                sed "s|^|$rel:|" || true
        done
} > "$TMP"

if [[ "$MODE" == "--check" ]]; then
    if [[ -f "$OUTPUT" ]] && cmp -s "$TMP" "$OUTPUT"; then
        echo "Context code index is current."
        exit 0
    fi
    echo "Context code index is stale. Run ./scripts/update-context.sh" >&2
    exit 1
fi

if [[ -f "$OUTPUT" ]] && cmp -s "$TMP" "$OUTPUT"; then
    echo "Context code index is already current."
else
    mv "$TMP" "$OUTPUT"
    echo "Updated .codex/context/CODE_INDEX.md"
fi
